In [1]:
import torch
import numpy as np

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [2]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.9088, -0.6608,  1.2810],
        [-1.3146,  0.4691, -1.6473]], requires_grad=True)
tensor([ 0.1177, -0.5800], requires_grad=True)


In [3]:
def model(x):
    return x @ w.t() + b

In [4]:
# Generate predictions
preds = model(inputs)
print(preds)
# Compare with targets
print(targets)

tensor([[  77.2725, -135.9531],
        [ 106.6562, -184.3591],
        [  64.9363, -147.6378],
        [ 111.8026, -175.4519],
        [  89.0613, -161.5683]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [6]:
# Train for 100 epochs
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [7]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(33.5669, grad_fn=<DivBackward0>)


In [8]:
print(preds)
print(targets)

tensor([[ 56.9551,  70.8458],
        [ 84.3481,  95.3917],
        [114.1614, 144.0988],
        [ 19.9894,  40.1104],
        [106.3032, 108.0385]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
