In [48]:
import torch
import numpy as np

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [49]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 1.0151, -0.8425, -0.1903],
        [-0.8286, -1.4912, -1.9319]], requires_grad=True)
tensor([-2.3962,  0.1801], requires_grad=True)


In [50]:
def model(x):
    return x @ w.t() + b

In [51]:
# Generate predictions
preds = model(inputs)
print(preds)
# Compare with targets
print(targets)

tensor([[   7.0759, -243.2835],
        [   3.6592, -330.0815],
        [ -38.0120, -383.7693],
        [  57.8732, -219.9326],
        [ -26.5535, -335.3737]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [52]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [53]:
# Train for 100 epochs
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [54]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(21.9685, grad_fn=<DivBackward0>)


In [55]:
print(preds)
print(targets)

tensor([[ 56.9564,  70.8868],
        [ 81.1140,  96.2435],
        [121.5068, 142.0978],
        [ 22.1084,  39.6948],
        [ 98.9460, 109.9125]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
