In [2]:
import torch
import numpy as np

# Input (temp, rainfall, humidity)
# inputs = np.array([[73, 67, 43], 
#                    [91, 88, 64], 
#                    [87, 134, 58], 
#                    [102, 43, 37], 
#                    [69, 96, 70]], dtype='float32')

# # Targets (apples, oranges)
# targets = np.array([[56, 70], 
#                     [81, 101], 
#                     [119, 133], 
#                     [22, 37], 
#                     [103, 119]], dtype='float32')
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
from torch.utils.data import TensorDataset
# Define dataset
train_ds = TensorDataset(inputs, targets)

In [4]:
from torch.utils.data import DataLoader
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [13]:
import torch.nn as nn
# Define model
model = nn.Linear(3,2)
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0498, -0.4404, -0.4871],
         [-0.4451, -0.2754, -0.5750]], requires_grad=True),
 Parameter containing:
 tensor([0.1848, 0.2564], requires_grad=True)]

In [6]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-22.5845,  28.4359],
        [-33.3895,  31.6259],
        [-50.3992,  39.8213],
        [ -3.5552,  41.7191],
        [-44.3226,  19.2329],
        [-21.9321,  28.7741],
        [-33.3426,  31.0191],
        [-50.4844,  39.8808],
        [ -4.2075,  41.3810],
        [-44.9281,  18.2880],
        [-22.5376,  27.8291],
        [-32.7372,  31.9640],
        [-50.4461,  40.4281],
        [ -2.9497,  42.6641],
        [-44.9749,  18.8948]], grad_fn=<AddmmBackward0>)

In [7]:
# Import nn.functional
import torch.nn.functional as F
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(9540.1309, grad_fn=<MseLossBackward0>)


In [8]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [9]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [10]:
fit(200, model, loss_fn, opt, train_dl)

Epoch [10/200], Loss: 937.2238
Epoch [20/200], Loss: 87.9819
Epoch [30/200], Loss: 397.6464
Epoch [40/200], Loss: 388.4802
Epoch [50/200], Loss: 350.0872
Epoch [60/200], Loss: 84.2106
Epoch [70/200], Loss: 13.8243
Epoch [80/200], Loss: 97.1375
Epoch [90/200], Loss: 18.2088
Epoch [100/200], Loss: 87.1902
Epoch [110/200], Loss: 125.6232
Epoch [120/200], Loss: 68.6839
Epoch [130/200], Loss: 29.2794
Epoch [140/200], Loss: 42.9614
Epoch [150/200], Loss: 48.2717
Epoch [160/200], Loss: 43.3112
Epoch [170/200], Loss: 18.5498
Epoch [180/200], Loss: 30.7757
Epoch [190/200], Loss: 28.5104
Epoch [200/200], Loss: 20.7899
