In [45]:
import torch
import numpy as np

# Input (temp, rainfall, humidity)
# inputs = np.array([[73, 67, 43], 
#                    [91, 88, 64], 
#                    [87, 134, 58], 
#                    [102, 43, 37], 
#                    [69, 96, 70]], dtype='float32')

# # Targets (apples, oranges)
# targets = np.array([[56, 70], 
#                     [81, 101], 
#                     [119, 133], 
#                     [22, 37], 
#                     [103, 119]], dtype='float32')
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [46]:
from torch.utils.data import TensorDataset
# Define dataset
train_ds = TensorDataset(inputs, targets)

In [47]:
from torch.utils.data import DataLoader
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [48]:
import torch.nn as nn
# Define model
model = nn.Linear(3, 2)
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2611, -0.1857,  0.4788],
         [-0.2354, -0.0800,  0.4190]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1175, -0.3538], requires_grad=True)]

In [49]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 27.3196,  -4.8757],
        [ 38.1726,  -1.9922],
        [ 25.7113,  -7.2442],
        [ 36.4770, -12.2955],
        [ 33.8149,   5.0599],
        [ 27.7664,  -5.0310],
        [ 38.8372,  -1.4932],
        [ 26.4512,  -7.0605],
        [ 36.0302, -12.1401],
        [ 34.0326,   5.7142],
        [ 27.9841,  -4.3767],
        [ 38.6195,  -2.1476],
        [ 25.0468,  -7.7432],
        [ 36.2594, -12.9499],
        [ 33.3681,   5.2152]], grad_fn=<AddmmBackward0>)

In [50]:
# Import nn.functional
import torch.nn.functional as F
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(6745.7612, grad_fn=<MseLossBackward0>)


In [51]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [52]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [53]:
fit(200, model, loss_fn, opt, train_dl)

Epoch [10/200], Loss: 435.0196
Epoch [20/200], Loss: 425.7869
Epoch [30/200], Loss: 172.1568
Epoch [40/200], Loss: 126.3665
Epoch [50/200], Loss: 81.8263
Epoch [60/200], Loss: 31.7627
Epoch [70/200], Loss: 66.9900
Epoch [80/200], Loss: 10.8081
Epoch [90/200], Loss: 16.6878
Epoch [100/200], Loss: 9.4493
Epoch [110/200], Loss: 12.8509
Epoch [120/200], Loss: 7.0073
Epoch [130/200], Loss: 5.6361
Epoch [140/200], Loss: 3.2247
Epoch [150/200], Loss: 1.8268
Epoch [160/200], Loss: 1.8636
Epoch [170/200], Loss: 2.3990
Epoch [180/200], Loss: 2.5043
Epoch [190/200], Loss: 1.3201
Epoch [200/200], Loss: 1.1801
